export interface DiagramTypeDefinition {
  id: string;
  displayName: string;
  canonicalType: string;
  description: string;
  category: string;
  referenceFile: string;
  exampleAsset: string;
}
export const diagramTypes: DiagramTypeDefinition[] = [
  {
    id: "architecture",
    displayName: "Architecture",
    canonicalType: "architecture",
    description: "Components + connections in a system",
    category: "Essential",
    referenceFile: "type-architecture.md",
    exampleAsset: "example-architecture.html",
  },
  {
    id: "it-state",
    displayName: "IT current-state",
    canonicalType: "it-state",
    description:
      "Legacy IT landscape grouped by phase/department; documents the *before* state in modernization proposals",
    category: "Advanced",
    referenceFile: "type-it-state.md",
    exampleAsset: "example-it-state.html",
  },
  {
    id: "flowchart",
    displayName: "Flowchart",
    canonicalType: "flowchart",
    description: "Decision logic with branches",
    category: "Essential",
    referenceFile: "type-flowchart.md",
    exampleAsset: "example-flowchart.html",
  },
  {
    id: "activity",
    displayName: "Activity Diagram",
    canonicalType: "flowchart",
    description: "Actions, decisions and branches in a workflow.",
    category: "Essential",
    referenceFile: "type-flowchart.md",
    exampleAsset: "example-flowchart.html",
  },
  {
    id: "methodology",
    displayName: "Methodology Diagram",
    canonicalType: "process",
    description: "Development or research stages and their outcomes.",
    category: "Essential",
    referenceFile: "type-process.md",
    exampleAsset: "example-process.html",
  },
  {
    id: "sequence",
    displayName: "Sequence",
    canonicalType: "sequence",
    description: "Time-ordered messages between actors",
    category: "Essential",
    referenceFile: "type-sequence.md",
    exampleAsset: "example-sequence.html",
  },
  {
    id: "state",
    displayName: "State machine",
    canonicalType: "state",
    description: "States + transitions + guards",
    category: "Essential",
    referenceFile: "type-state.md",
    exampleAsset: "example-state.html",
  },
  {
    id: "er",
    displayName: "ER / data model",
    canonicalType: "er",
    description: "Entities + fields + relationships",
    category: "Essential",
    referenceFile: "type-er.md",
    exampleAsset: "example-er.html",
  },
  {
    id: "timeline",
    displayName: "Timeline",
    canonicalType: "timeline",
    description: "Events positioned in time",
    category: "Advanced",
    referenceFile: "type-timeline.md",
    exampleAsset: "example-timeline.html",
  },
  {
    id: "swimlane",
    displayName: "Swimlane",
    canonicalType: "swimlane",
    description: "Cross-functional process with handoffs",
    category: "Advanced",
    referenceFile: "type-swimlane.md",
    exampleAsset: "example-swimlane.html",
  },
  {
    id: "quadrant",
    displayName: "Quadrant",
    canonicalType: "quadrant",
    description: "Two-axis positioning / prioritization",
    category: "Advanced",
    referenceFile: "type-quadrant.md",
    exampleAsset: "example-quadrant.html",
  },
  {
    id: "radar",
    displayName: "Radar / Spider",
    canonicalType: "radar",
    description: "Multiple entities scored across 3–5 quantitative criteria",
    category: "Advanced",
    referenceFile: "type-radar.md",
    exampleAsset: "example-radar.html",
  },
  {
    id: "polar",
    displayName: "Polar chart",
    canonicalType: "polar",
    description:
      "One quantitative series across cyclic categories; angle=category, radius=magnitude",
    category: "Advanced",
    referenceFile: "type-polar.md",
    exampleAsset: "example-polar.html",
  },
  {
    id: "loop",
    displayName: "Loop",
    canonicalType: "loop",
    description:
      "Reinforcing cycle / flywheel where the last step feeds the first and a shared hub accumulates state",
    category: "Advanced",
    referenceFile: "type-loop.md",
    exampleAsset: "example-loop.html",
  },
  {
    id: "nested",
    displayName: "Nested",
    canonicalType: "nested",
    description: "Hierarchy through containment / scope",
    category: "Advanced",
    referenceFile: "type-nested.md",
    exampleAsset: "example-nested.html",
  },
  {
    id: "tree",
    displayName: "Tree",
    canonicalType: "tree",
    description: "Parent → children relationships",
    category: "Advanced",
    referenceFile: "type-tree.md",
    exampleAsset: "example-tree.html",
  },
  {
    id: "org-chart",
    displayName: "Org chart",
    canonicalType: "org-chart",
    description: "Human/agent/team ownership, reporting, routing, escalation",
    category: "Advanced",
    referenceFile: "type-org-chart.md",
    exampleAsset: "example-org-chart.html",
  },
  {
    id: "layers",
    displayName: "Layer stack",
    canonicalType: "layers",
    description: "Stacked abstraction levels",
    category: "Advanced",
    referenceFile: "type-layers.md",
    exampleAsset: "example-layers.html",
  },
  {
    id: "venn",
    displayName: "Venn",
    canonicalType: "venn",
    description: "Overlap between sets",
    category: "Advanced",
    referenceFile: "type-venn.md",
    exampleAsset: "example-venn.html",
  },
  {
    id: "pyramid",
    displayName: "Pyramid / funnel",
    canonicalType: "pyramid",
    description: "Ranked hierarchy or conversion drop-off",
    category: "Advanced",
    referenceFile: "type-pyramid.md",
    exampleAsset: "example-pyramid.html",
  },
  {
    id: "bar",
    displayName: "Bar chart",
    canonicalType: "bar",
    description: "Quantitative comparison across categories",
    category: "Advanced",
    referenceFile: "type-bar.md",
    exampleAsset: "example-bar.html",
  },
  {
    id: "treemap",
    displayName: "Treemap",
    canonicalType: "treemap",
    description: "Part-of-whole where the relative sizes are the story",
    category: "Advanced",
    referenceFile: "type-treemap.md",
    exampleAsset: "example-treemap.html",
  },
  {
    id: "line",
    displayName: "Line chart",
    canonicalType: "line",
    description:
      "Continuous trends over time, change between exactly two states (slopegraph), one distribution per series (ridgeline), or rank movement across several snapshots (bump)",
    category: "Advanced",
    referenceFile: "type-line.md",
    exampleAsset: "example-line.html",
  },
  {
    id: "gantt",
    displayName: "Gantt",
    canonicalType: "gantt",
    description: "Tasks and phases on a timeline",
    category: "Advanced",
    referenceFile: "type-gantt.md",
    exampleAsset: "example-gantt.html",
  },
  {
    id: "scatter",
    displayName: "Scatter plot",
    canonicalType: "scatter",
    description:
      "Distribution and correlation between two variables, three with area-sized marks (bubble), or one variable with a dot per item (beeswarm)",
    category: "Advanced",
    referenceFile: "type-scatter.md",
    exampleAsset: "example-scatter.html",
  },
  {
    id: "high-level",
    displayName: "High-Level",
    canonicalType: "high-level",
    description: "End-to-end data stack on a container cluster",
    category: "Essential",
    referenceFile: "type-high-level.md",
    exampleAsset: "example-high-level.html",
  },
  {
    id: "process",
    displayName: "Process",
    canonicalType: "process",
    description: "Multi-actor sequential process with data handoffs",
    category: "Advanced",
    referenceFile: "type-process.md",
    exampleAsset: "example-process.html",
  },
  {
    id: "medallion",
    displayName: "Medallion",
    canonicalType: "medallion",
    description:
      "Multi-tier data storage with quality levels and access policies",
    category: "Advanced",
    referenceFile: "type-medallion.md",
    exampleAsset: "example-medallion.html",
  },
  {
    id: "data-flow",
    displayName: "Data flow",
    canonicalType: "data-flow",
    description: "Role-scoped data flow: who does what at each pipeline step",
    category: "Essential",
    referenceFile: "type-data-flow.md",
    exampleAsset: "example-data-flow.html",
  },
  {
    id: "dp-integration",
    displayName: "DP integration",
    canonicalType: "dp-integration",
    description:
      "Integration topology of a data platform — sources → core → consumers",
    category: "Advanced",
    referenceFile: "type-dp-integration.md",
    exampleAsset: "example-dp-integration.html",
  },
  {
    id: "dp-security-matrix",
    displayName: "DP security matrix",
    canonicalType: "dp-security-matrix",
    description: "Per-role / per-component access permissions matrix",
    category: "Advanced",
    referenceFile: "type-dp-security-matrix.md",
    exampleAsset: "example-dp-security-matrix.html",
  },
  {
    id: "sankey",
    displayName: "Sankey",
    canonicalType: "sankey",
    description:
      "A quantity splitting and merging across stages, band width = amount",
    category: "Advanced",
    referenceFile: "type-sankey.md",
    exampleAsset: "example-sankey.html",
  },
  {
    id: "fishbone",
    displayName: "Fishbone",
    canonicalType: "fishbone",
    description:
      "Causes of one observed effect, grouped by category (root-cause analysis)",
    category: "Advanced",
    referenceFile: "type-fishbone.md",
    exampleAsset: "example-fishbone.html",
  },
  {
    id: "wardley",
    displayName: "Wardley map",
    canonicalType: "wardley",
    description:
      "Value chain against evolution — what to build, buy, and what is moving",
    category: "Advanced",
    referenceFile: "type-wardley.md",
    exampleAsset: "example-wardley.html",
  },
  {
    id: "kanban",
    displayName: "Kanban",
    canonicalType: "kanban",
    description: "Work-in-progress by state, with WIP limits and blocked items",
    category: "Advanced",
    referenceFile: "type-kanban.md",
    exampleAsset: "example-kanban.html",
  },
  {
    id: "journey",
    displayName: "User journey",
    canonicalType: "journey",
    description:
      "What a person does across stages of an experience, and how it feels",
    category: "Advanced",
    referenceFile: "type-journey.md",
    exampleAsset: "example-journey.html",
  },
  {
    id: "deployment",
    displayName: "Deployment",
    canonicalType: "deployment",
    description:
      "Where software runs — zones, hosts, artifacts, replicas, ports",
    category: "Essential",
    referenceFile: "type-deployment.md",
    exampleAsset: "example-deployment.html",
  },
  {
    id: "dependency",
    displayName: "Dependency graph",
    canonicalType: "dependency",
    description:
      "What depends on what, with fan-in and cycles a tree cannot express",
    category: "Advanced",
    referenceFile: "type-dependency.md",
    exampleAsset: "example-dependency.html",
  },
  {
    id: "uml-class",
    displayName: "UML class",
    canonicalType: "uml-class",
    description:
      "Classes with operations, inheritance, composition (other UML routes elsewhere)",
    category: "Essential",
    referenceFile: "type-uml-class.md",
    exampleAsset: "example-uml-class.html",
  },
  {
    id: "story-map",
    displayName: "Story map",
    canonicalType: "story-map",
    description: "Narrative backbone sliced into releases, with the cut line",
    category: "Advanced",
    referenceFile: "type-story-map.md",
    exampleAsset: "example-story-map.html",
  },
  {
    id: "db-schema",
    displayName: "Database schema",
    canonicalType: "db-schema",
    description:
      "Physical tables: SQL types, constraints, indexes, column-level FKs",
    category: "Essential",
    referenceFile: "type-db-schema.md",
    exampleAsset: "example-db-schema.html",
  },
];
export function getDiagramType(id: string) {
  const type = diagramTypes.find((t) => t.id === id);
  if (!type) throw new Error("Unknown diagram type.");
  return type;
}
